---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# The design of statistical software
### NUMBATs Seminar (2023-03-23)

<!-- badges: start -->
<!-- badges: end -->

Slides and notes for a seminar presentation at the Monash University NUMBATs seminar on the 23rd of March 2023.

#### Abstract

The design of software varies drastically by domain, language, and the individual developer.
* Good code, bad code (smell and feel)
* R, Python, Julia, C++
* Base R, tidy R

#### Structure

* Human interface devices (HID) for statistical computing (point and click, VR, focus on writing code)
* Variability of code design by domain, language, and author
* Differences in code domain (math, statistics, websites, data)
* Differences in code language (R, Python, Julia, C++... prophet example for how it can go wrong)
* Differences by developer (Base R, Tidy R - good code, bad code)
* Tips for writing good code and avoiding bad code (mostly for R, but with some generality to the style of other languages)

#### Format

30 minute seminar followed by a 15 minute Q&A.

#### Bio

Mitchell O'Hara-Wild (he/him) is a PhD student, teaching associate and research assistant at Monash University with particular expertise in R package development, data analysis and statistical computing. He holds a Bachelor of Commerce (Honours) with a major in econometrics, and a Bachelor of Science majoring in computational science and mathematical statistics. Mitchell is the developer of several widely used R packages and operates a data consultancy which runs workshops, explores data, and writes software tools.
